from tkinter import *
root=Tk()
# icon=PhotoImage(file='Icon.png')
# root.iconphoto(True,icon)
root.iconbitmap('Icon.ico')
photo=PhotoImage(file='tam.png')
def Cong():
    x=int(a.get())
    y=int(b.get())
    c.set(str(x+y))
def Tru():
    x=int(a.get())
    y=int(b.get())
    c.set(str(x-y))
def Nhan():
    x=int(a.get())
    y=int(b.get())
    c.set(str(x*y))
def Chia():
    x=int(a.get())
    y=int(b.get())
    c.set(str(x/y))
a=StringVar()
b=StringVar()
c=StringVar()
root.title("Calculator")
root.resizable(height=True,width=True)
root.geometry('500x500')
Label(root,text='CONG TRU NHAN CHIA',fg='red',font=('Arian 18'),image=photo,compound='left').grid(row=0,columnspan=3)
nut=Frame(root)
Button(nut,text='Cong',command=Cong).pack(side='bottom',fill=X)
Button(nut,text='Tru',command=Tru).pack(side='bottom',fill=X)
Button(nut,text='Nhan',command=Nhan).pack(side='bottom',fill=X)
Button(nut,text='Chia',command=Chia).pack(side='bottom',fill=X)
nut.grid(rowspan=4,column=0)
Label(root,text='So a').grid(row=1,column=1)
Label(root,text='So b').grid(row=2,column=1)
Label(root,text='Ket qua').grid(row=3,column=1)
Entry(root,width=20,textvariable=a).grid(row=1,column=2)
Entry(root,width=20,textvariable=b).grid(row=2,column=2)
Entry(root,width=20,textvariable=c).grid(row=3,column=2)
Button(root,text='Thoat',width=10,fg='red',bg='blue',command=quit).grid(row=4,column=2)
root.mainloop()