from tkinter import *
root=Tk()
global t
def HienThi(t):
    if t<18.5:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'duoi chuan')
        htnguyco.insert(0,'Gay')
    elif t<24.9:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'Chuan')
        htnguyco.insert(0,'Binh thuong')
    elif t==25:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'Thua Can')
        htnguyco.insert(0,'Thua Can')
    elif t<29.9:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'Thua Can')
        htnguyco.insert(0,'Tien Beo Phi')
    elif t<34.9:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'Beo')
        htnguyco.insert(0,'Beo Phi Cap I')
    elif t<39.9:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'Beo')
        htnguyco.insert(0,'Beo Phi Cap II')
    else:
        httinhtrang.delete(0,END)
        htnguyco.delete(0,END)
        httinhtrang.insert(0,'Rat Beo')
        htnguyco.insert(0,'Rat Beo Phi III')
def Tinhbmi():
    y=float(ent1.get())
    x=float(ent2.get())
    z=x/y**2
    bmi.delete(0,END)
    t=round(z,3)
    bmi.insert(0,t)
    HienThi(t)

root.title("BMI")
root.geometry('400x400')
root.iconbitmap('Icon.ico')
root.config(bg='yellow')
chieucao=Label(root,text='Chieu cao',width=12,fg='black',font=('Arian 14'))
chieucao.place(y=10)
cannang=Label(root,text='Can nang',width=12,fg='black',font=('Arian 14'))
cannang.place(y=50)
ent1=Entry(root,width=30,bd=2)
ent1.place(y=12,x=160)
ent2=Entry(root,width=30,bd=2)
ent2.place(y=52,x=160)
tinh=Button(root,text='BMI',bg='blue',bd=4,width=12,command=Tinhbmi)
tinh.place(y=90,x=160)
Result=Label(root,text='BMI cua ban',width=12,fg='black',font=('Arian 14'))
Result.place(y=140)
bmi=Entry(root,width=30,bd=2)
bmi.place(y=140,x=160)
tinhtrang=Label(root,text='Tinh trang',width=12,fg='black',font=('Arian 14'))
tinhtrang.place(y=200)
nguyco=Label(root,text='Nguy co',width=12,fg='black',font=('Arian 14'))
nguyco.place(y=260)
httinhtrang=Entry(root,width=30,bd=2)
httinhtrang.place(y=200,x=160)
htnguyco=Entry(root,width=30,bd=2)
htnguyco.place(y=260,x=160)
root.mainloop()