from tkinter import *
root=Tk()
root.title("May Tinh")
# root.iconbitmap('Icon.ico')
root.geometry('300x200')
def Click(a):
    result=ent.get()
    ent.delete(0,END)
    ent.insert(0,str(result)+str(a))
def Tinh():
    pt=ent.get()
    ent.delete(0,END)
    kq=eval(pt)
    ent.insert(0,str(kq))
def Clear():
    ent.delete(0,END)
ent=Entry(root,width=50,borderwidth=3)
ent.grid(row=0,columnspan=3)
hang1=Frame(root)
Button(hang1,text='1',width=12,command=lambda:Click(1)).pack(side="left",fill=X)
Button(hang1,text='2',width=12,command=lambda:Click(2)).pack(side="left",fill=X)
Button(hang1,text='3',width=12,command=lambda:Click(3)).pack(side="left",fill=X)
hang1.grid(row=1,columnspan=3)
hang2=Frame(root)
Button(hang2,text='4',width=12,command=lambda:Click(4)).grid(row=2,column=0)
Button(hang2,text='5',width=12,command=lambda:Click(5)).grid(row=2,column=1)
Button(hang2,text='6',width=12,command=lambda:Click(6)).grid(row=2,column=2)
hang2.grid(row=2,columnspan=3)
hang3=Frame(root)
Button(hang3,text='7',width=12,command=lambda:Click(7)).grid(row=3,column=0)
Button(hang3,text='8',width=12,command=lambda:Click(8)).grid(row=3,column=1)
Button(hang3,text='9',width=12,command=lambda:Click(9)).grid(row=3,column=2)
hang3.grid(row=3,columnspan=3)
pheptinh=Frame(root)
Button(pheptinh,text='+',width=9,command=lambda:Click('+')).pack(side="left",fill=Y)
Button(pheptinh,text='-',width=9,command=lambda:Click('-')).pack(side="left",fill=Y)
Button(pheptinh,text='*',width=9,command=lambda:Click('*')).pack(side="left",fill=Y)
Button(pheptinh,text='/',width=9,command=lambda:Click('/')).pack(side="left",fill=Y)
pheptinh.grid(row=4,columnspan=3)
hang4=Frame(root)
Button(hang4,text='Clear',width=20,command=Clear).pack(side="left",fill=X)
Button(hang4,text='=',width=20,command=Tinh).pack(side="left",fill=X)
hang4.grid(row=5,columnspan=3)
# Button(phim,text='0').grid(row=1,column=1)
# Button(phim,text='1').grid(row=1,column=1)
root.mainloop()